### PR TITLE
Apply last example_ynh

### PR DESCRIPTION
**Pull request by yalh76**
## Problem

- *Bullseye level0*

## Solution

- *Apply last example_ynh*
- *Fix dependencies for bullseye removing `python-dev` as `python3-dev` is already here*

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by mhfowler** [comment]
!testme

**Comment by mhfowler** [comment]
@yalh76 @alexAubin sorry I was offline for a couple weeks. This looks good!

**Comment by mhfowler** [comment]
glad you merged it

**Comment by yalh76** [comment]
your welcome ;)

**Pull request merged**
